version: "3.8"

services:
  api-01: &api
    image: densyy/api-rinha-backend:latest
    hostname: api-01
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"
