version: "3.8"

services:
  haproxy:
    image: haproxy:latest
    hostname: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api_01
      - api_02
    ports:
      - "9999:9999"
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "20MB"

  api_01: &api
    image: densyy/api-rinha-backend:latest
    hostname: api_01
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"

  api_02:
    <<: *api
    hostname: api_02
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=user
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"
