version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-01
      - api-02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"

  api-01: &api
    image: densyy/api-rinha-backend:latest
    hostname: api-01
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"

  api-02:
    <<: *api
    hostname: api-02
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

networks:
  default:
    driver: host
    name: rinha-nginx-2024
