version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-01
      - api-02
    ports:
      - "9999:9999"
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"

  api01: &api
    image: densyy/api-rinha-backend:latest
    hostname: api01
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
